// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Lib.Entity;

public partial class invoice_operation_type
{
    public int id { get; set; }

    public string operation_type { get; set; }

    public string operation_name { get; set; }

    public string description { get; set; }

    public virtual ICollection<invoice_record> invoice_record { get; set; } = new List<invoice_record>();
}