// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Lib.Entity;

public partial class invoice_number_management
{
    public int id { get; set; }

    public int year { get; set; }

    public int term { get; set; }

    public string letter { get; set; }

    public int start_number { get; set; }

    public int end_number { get; set; }

    public int now_number { get; set; }

    public DateTime? create_date { get; set; }

    public int status_id { get; set; }

    public DateTime? update_date { get; set; }

    public int system_code_id { get; set; }

    public virtual invoice_number_status status { get; set; }

    public virtual invoice_system_code system_code { get; set; }
}