// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Lib.Entity;

public partial class invoice_record
{
    public int id { get; set; }

    public int year { get; set; }

    public int term { get; set; }

    public string invoice_number { get; set; }

    public string invoice_time { get; set; }

    public string invoice_date { get; set; }

    public string invoice_type { get; set; }

    public string donate_mark { get; set; }

    public string print_mark { get; set; }

    public string random_number { get; set; }

    public string buyer_identifier { get; set; }

    public string buyer_name { get; set; }

    public decimal sales_amount { get; set; }

    public decimal free_tax_sales_amount { get; set; }

    public decimal zero_tax_sales_amount { get; set; }

    public string tax_type { get; set; }

    public decimal tax_rate { get; set; }

    public decimal tax_amount { get; set; }

    public decimal total_amount { get; set; }

    public string order_no { get; set; }

    public string reason { get; set; }

    public bool send_status { get; set; }

    public int operation_type_id { get; set; }

    public DateTime create_date { get; set; }

    public DateTime update_date { get; set; }

    public string carrier_type { get; set; }

    public int user_serial_map_id { get; set; }

    public string carrier_id_1 { get; set; }

    public int system_code_id { get; set; }

    public virtual ICollection<invoice_product_record> invoice_product_record { get; set; } = new List<invoice_product_record>();

    public virtual invoice_operation_type operation_type { get; set; }

    public virtual invoice_system_code system_code { get; set; }

    public virtual invoice_system_user_serial_map user_serial_map { get; set; }
}