// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Lib.Entity;

public partial class welldone_common_log
{
    public long id { get; set; }

    public string project { get; set; }

    public string action { get; set; }

    public string log_level { get; set; }

    public string session { get; set; }

    public string user_id { get; set; }

    public string log_content { get; set; }

    public string remark { get; set; }

    public string ip_address { get; set; }

    public DateTime create_date { get; set; }
}