// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Entity;

public partial class invoice_system_code
{
    public int id { get; set; }

    public string system_code { get; set; }

    public string system_name { get; set; }

    public string seller_identifier { get; set; }

    public string seller_name { get; set; }

    public string seller_address { get; set; }

    public string seller_telephone_number { get; set; }

    public virtual ICollection<invoice_number_management> invoice_number_management { get; set; } = new List<invoice_number_management>();

    public virtual ICollection<invoice_record> invoice_record { get; set; } = new List<invoice_record>();

    public virtual ICollection<invoice_system_user_max_serial> invoice_system_user_max_serial { get; set; } = new List<invoice_system_user_max_serial>();

    public virtual ICollection<invoice_system_user_serial_map> invoice_system_user_serial_map { get; set; } = new List<invoice_system_user_serial_map>();
}