// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Entity;

public partial class invoice_product_record
{
    public int id { get; set; }

    public int invoice_record_id { get; set; }

    public string description { get; set; }

    public int quantity { get; set; }

    public string unit { get; set; }

    public decimal unit_price { get; set; }

    public decimal amount { get; set; }

    public int sequence_number { get; set; }

    public virtual invoice_record invoice_record { get; set; }
}