// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Entity;

public partial class invoice_number_status
{
    public int id { get; set; }

    public string status_name { get; set; }

    public virtual ICollection<invoice_number_management> invoice_number_management { get; set; } = new List<invoice_number_management>();
}