// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InvoiceAPI.Entity;

public partial class invoice_system_user_max_serial
{
    public int id { get; set; }

    public int system_code_id { get; set; }

    public int serial_no { get; set; }

    public byte[] row_version { get; set; }

    public virtual invoice_system_code system_code { get; set; }
}