// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace InvoiceAPI.Entity;

public partial class WelldoneContext : DbContext
{
    public WelldoneContext(DbContextOptions<WelldoneContext> options)
        : base(options)
    {
    }

    public virtual DbSet<invoice_number_management> invoice_number_management { get; set; }

    public virtual DbSet<invoice_number_status> invoice_number_status { get; set; }

    public virtual DbSet<invoice_operation_type> invoice_operation_type { get; set; }

    public virtual DbSet<invoice_product_record> invoice_product_record { get; set; }

    public virtual DbSet<invoice_record> invoice_record { get; set; }

    public virtual DbSet<invoice_system_code> invoice_system_code { get; set; }

    public virtual DbSet<invoice_system_user_max_serial> invoice_system_user_max_serial { get; set; }

    public virtual DbSet<invoice_system_user_serial_map> invoice_system_user_serial_map { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<invoice_number_management>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__invoice___3213E83F7AA384E0");

            entity.Property(e => e.create_date).HasColumnType("datetime");
            entity.Property(e => e.letter).HasMaxLength(50);
            entity.Property(e => e.update_date).HasColumnType("datetime");

            entity.HasOne(d => d.status).WithMany(p => p.invoice_number_management)
                .HasForeignKey(d => d.status_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceManagementStatus");

            entity.HasOne(d => d.system_code).WithMany(p => p.invoice_number_management)
                .HasForeignKey(d => d.system_code_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_invoice_number_management_invoice_system_code");
        });

        modelBuilder.Entity<invoice_number_status>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__invoice___3683B5313270A797");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.status_name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<invoice_operation_type>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__invoice___5232BAE1FC674F5E");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.description).HasMaxLength(200);
            entity.Property(e => e.operation_name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.operation_type)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<invoice_product_record>(entity =>
        {
            entity.Property(e => e.amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.unit)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.unit_price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.invoice_record).WithMany(p => p.invoice_product_record)
                .HasForeignKey(d => d.invoice_record_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_invoice_product_record_invoice_record");
        });

        modelBuilder.Entity<invoice_record>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__invoice___3213E83F171FE602");

            entity.Property(e => e.buyer_identifier)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("0000000000");
            entity.Property(e => e.buyer_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.carrier_id_1)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.carrier_type)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.create_date).HasColumnType("datetime");
            entity.Property(e => e.donate_mark)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("0");
            entity.Property(e => e.free_tax_sales_amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.invoice_date)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.invoice_number)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.invoice_time)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.invoice_type)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasDefaultValue("07");
            entity.Property(e => e.order_no)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.print_mark)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("Y");
            entity.Property(e => e.random_number)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.reason).HasMaxLength(500);
            entity.Property(e => e.sales_amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.tax_amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.tax_rate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.tax_type)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.total_amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.update_date).HasColumnType("datetime");
            entity.Property(e => e.zero_tax_sales_amount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.operation_type).WithMany(p => p.invoice_record)
                .HasForeignKey(d => d.operation_type_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_invoice_record_invoice_operation_type");

            entity.HasOne(d => d.system_code).WithMany(p => p.invoice_record)
                .HasForeignKey(d => d.system_code_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_invoice_record_invoice_system_code");

            entity.HasOne(d => d.user_serial_map).WithMany(p => p.invoice_record)
                .HasForeignKey(d => d.user_serial_map_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_invoice_record_invoice_system_user_serial_map");
        });

        modelBuilder.Entity<invoice_system_code>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__system_c__D652FF9911033E83");

            entity.HasIndex(e => e.system_code, "IX_invoice_system_code").IsUnique();

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.seller_address).HasMaxLength(200);
            entity.Property(e => e.seller_identifier)
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.seller_name).HasMaxLength(100);
            entity.Property(e => e.seller_telephone_number).HasMaxLength(20);
            entity.Property(e => e.system_code)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.system_name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<invoice_system_user_max_serial>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK_system_user_max_serial");

            entity.Property(e => e.row_version)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.system_code).WithMany(p => p.invoice_system_user_max_serial)
                .HasForeignKey(d => d.system_code_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_invoice_system_user_max_serial_invoice_system_code");
        });

        modelBuilder.Entity<invoice_system_user_serial_map>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK_system_user_serial_map");

            entity.HasIndex(e => new { e.system_code_id, e.user_id, e.serial_no }, "UQ_system_code_user_serial").IsUnique();

            entity.Property(e => e.user_id)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.system_code).WithMany(p => p.invoice_system_user_serial_map)
                .HasForeignKey(d => d.system_code_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_invoice_system_user_serial_map_invoice_system_code");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}